baseURL = "https://memo.rokuzeudon.com/"
canonifyURLs = true
buildDrafts = false
title = "6z"
languageCode = "ja"

[taxonomies]
  category = "categories"
  tag = "tags"

[Params]
  description = "@rokuzeudon のWebに関するメモブログです"
  author = "rokuzeudon"
  twitter_account = "rokuzeudon"
  github_account = "rokuzeudon"
