# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Lunacy"
license = "MIT"
licenselink = "https://github.com/christat/Lunacy/blob/master/LICENSE"
description = "A minimal Hugo theme; Blog-purposed"
homepage = "http://christat.me/Lunacy/"
tags = ["blog", "pagination", "minimal design", "responsive"]
min_version = 0.14

[author]
  name = "Chris Statkiewicz"
  homepage = "http://christat.me/"
